name: Paul Withers Blog
title: Paul Withers Blog
markdown: kramdown
repository: paulswithers/paulswithers.github.io
github: [metadata]
permalink: /blog/:year/:month/:day/:title
author: Paul Withers
plugins:
  - jekyll-feed
collections:
  - bio_categories