name: Paul Withers' Blog
title: Paul Withers' Blog
description: A blog about various HCL software and related learning, from an Lifetime IBM Champion and former HCL Lifetime Ambassador
markdown: kramdown
repository: paulswithers/paulswithers.github.io
github: [metadata]
permalink: /blog/:year/:month/:day/:title
author: Paul Withers
url: "https://paulswithers.github.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap
collections:
  - bio_categories